import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.5'
	id 'io.spring.dependency-management' version '1.1.7'

	// Kotlin 플러그인 추가
	id 'org.jetbrains.kotlin.jvm' version '1.9.25'
	// Spring 클래스를 Kotlin에서 사용하기 위한 플러그인 추가
	id 'org.jetbrains.kotlin.plugin.spring' version '1.9.25'
	// JPA 엔티티를 위한 플러그인
	id 'org.jetbrains.kotlin.plugin.jpa' version '1.9.25'
}

group = 'io.github.hs96wings'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// 테스트 코드를 위한 의존성 추가
	testImplementation 'com.fasterxml.jackson.core:jackson-databind'

	// jwt 0.11버전 라이브러리 추가
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	// websocket 추가
	implementation 'org.springframework.boot:spring-boot-starter-websocket'

	// Kotlin 표준 라이브러리(stdlib) 의존성 추가
	implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
	// Kotlin 리플렉션 라이브러리 추가
	implementation 'org.jetbrains.kotlin:kotlin-reflect'
}

compileKotlin {
	compilerOptions {
		jvmTarget.set(JvmTarget.JVM_17)
	}
}

tasks.named('test') {
	useJUnitPlatform()
}